//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Iteration1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player
    {
        public Player()
        {
            this.HighScores = new HashSet<HighScores>();
        }
    
        public int PlayerID { get; set; }
        public string PlayerUsername { get; set; }
        public string PlayerPassword { get; set; }
    
        public virtual ICollection<HighScores> HighScores { get; set; }
    }
}
